[project]
name = "actividad-5"
version = "0.1.0"
description = ""
authors = [
    { name = "Ximena", email = "cindy.mendoza@axity.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic (>=2.13.5,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "sqlalchemy (>=2.1.1,<3.0.0)",
    "alembic (>=1.20.0,<2.0.0)",
    "fastapi (>=0.142.0,<0.143.0)",
    "aiohttp (>=3.14.3,<4.0.0)",
    "uvicorn (>=0.54.0,<0.55.0)",
    "pyjwt (>=2.15.1,<3.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
    "joblib (>=1.6.0,<2.0.0)",
    "typer (>=0.27.2,<0.28.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy (>=2.3.1,<3.0.0)",
    "ruff (>=0.16.9,<0.17.0)",
    "black (>=26.5.1,<27.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "hypothesis (>=6.168.3,<7.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pandas-stubs (>=3.0.5.260914,<4.0.0.0)",
    "joblib-stubs (>=1.5.3.1.20260117,<2.0.0.0.0)"
]

[tool.black]
target-version = ["py312"]

[tool.ruff]
target-version = "py312"
exclude = ["alembic"]
force-exclude = true

[tool.ruff.lint]
ignore = ["I001", "B008"]

[[tool.mypy.overrides]]
module = ["sklearn.*"]
disable_error_code = ["import-untyped"]