# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actividad_18/proto/orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "actividad_18/proto/orders.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1f\x61\x63tividad_18/proto/orders.proto\x12\x06orders"F\n\x12\x43reateOrderRequest\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t"c\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t2\x8c\x01\n\x0cOrderService\x12@\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponse\x12:\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "actividad_18.proto.orders_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREATEORDERREQUEST"]._serialized_start = 43
    _globals["_CREATEORDERREQUEST"]._serialized_end = 113
    _globals["_GETORDERREQUEST"]._serialized_start = 115
    _globals["_GETORDERREQUEST"]._serialized_end = 150
    _globals["_ORDERRESPONSE"]._serialized_start = 152
    _globals["_ORDERRESPONSE"]._serialized_end = 251
    _globals["_ORDERSERVICE"]._serialized_start = 254
    _globals["_ORDERSERVICE"]._serialized_end = 394
# @@protoc_insertion_point(module_scope)
